name: Deploy Django to EC2

on:
push:
branches:
- main

jobs:
deploy:
runs-on: ubuntu-latest

```
steps:
  - name: Checkout repository
    uses: actions/checkout@v4

  - name: Deploy to EC2 via SSH
    uses: appleboy/ssh-action@v0.1.6
    with:
      host: ${{ secrets.EC2_HOST }}
      username: ec2-user
      key: ${{ secrets.EC2_SSH_KEY }}
      port: 22
      script: |
        cd ~/latest_project
        git pull origin main

        source venv/bin/activate

        pip install -r requirements.txt

        python manage.py migrate
        python manage.py collectstatic --noinput

        sudo systemctl restart gunicorn
```
